/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignNewRouteImport } from './routes/design.new'
import { Route as DesignIdRefineRouteImport } from './routes/design.$id.refine'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignNewRoute = DesignNewRouteImport.update({
  id: '/design/new',
  path: '/design/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdRefineRoute = DesignIdRefineRouteImport.update({
  id: '/design/$id/refine',
  path: '/design/$id/refine',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/design/new': typeof DesignNewRoute
  '/design/$id/refine': typeof DesignIdRefineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/design/new': typeof DesignNewRoute
  '/design/$id/refine': typeof DesignIdRefineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/design/new': typeof DesignNewRoute
  '/design/$id/refine': typeof DesignIdRefineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/design/new' | '/design/$id/refine'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/design/new' | '/design/$id/refine'
  id: '__root__' | '/' | '/auth' | '/design/new' | '/design/$id/refine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DesignNewRoute: typeof DesignNewRoute
  DesignIdRefineRoute: typeof DesignIdRefineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/new': {
      id: '/design/new'
      path: '/design/new'
      fullPath: '/design/new'
      preLoaderRoute: typeof DesignNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id/refine': {
      id: '/design/$id/refine'
      path: '/design/$id/refine'
      fullPath: '/design/$id/refine'
      preLoaderRoute: typeof DesignIdRefineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DesignNewRoute: DesignNewRoute,
  DesignIdRefineRoute: DesignIdRefineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
