/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignsRouteImport } from './routes/designs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignNewRouteImport } from './routes/design.new'
import { Route as ApiGenerateRenderRouteImport } from './routes/api/generate-render'
import { Route as AdminReviewsRouteImport } from './routes/admin_.reviews'
import { Route as DesignIdReviewRouteImport } from './routes/design.$id.review'
import { Route as DesignIdRefineRouteImport } from './routes/design.$id.refine'
import { Route as DesignIdGalleryRouteImport } from './routes/design.$id.gallery'
import { Route as DesignIdViewIdxRouteImport } from './routes/design.$id.view.$idx'

const DesignsRoute = DesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignNewRoute = DesignNewRouteImport.update({
  id: '/design/new',
  path: '/design/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRenderRoute = ApiGenerateRenderRouteImport.update({
  id: '/api/generate-render',
  path: '/api/generate-render',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin_/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdReviewRoute = DesignIdReviewRouteImport.update({
  id: '/design/$id/review',
  path: '/design/$id/review',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdRefineRoute = DesignIdRefineRouteImport.update({
  id: '/design/$id/refine',
  path: '/design/$id/refine',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdGalleryRoute = DesignIdGalleryRouteImport.update({
  id: '/design/$id/gallery',
  path: '/design/$id/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdViewIdxRoute = DesignIdViewIdxRouteImport.update({
  id: '/design/$id/view/$idx',
  path: '/design/$id/view/$idx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/designs': typeof DesignsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/api/generate-render': typeof ApiGenerateRenderRoute
  '/design/new': typeof DesignNewRoute
  '/design/$id/gallery': typeof DesignIdGalleryRoute
  '/design/$id/refine': typeof DesignIdRefineRoute
  '/design/$id/review': typeof DesignIdReviewRoute
  '/design/$id/view/$idx': typeof DesignIdViewIdxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/designs': typeof DesignsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/api/generate-render': typeof ApiGenerateRenderRoute
  '/design/new': typeof DesignNewRoute
  '/design/$id/gallery': typeof DesignIdGalleryRoute
  '/design/$id/refine': typeof DesignIdRefineRoute
  '/design/$id/review': typeof DesignIdReviewRoute
  '/design/$id/view/$idx': typeof DesignIdViewIdxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/designs': typeof DesignsRoute
  '/admin_/reviews': typeof AdminReviewsRoute
  '/api/generate-render': typeof ApiGenerateRenderRoute
  '/design/new': typeof DesignNewRoute
  '/design/$id/gallery': typeof DesignIdGalleryRoute
  '/design/$id/refine': typeof DesignIdRefineRoute
  '/design/$id/review': typeof DesignIdReviewRoute
  '/design/$id/view/$idx': typeof DesignIdViewIdxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/designs'
    | '/admin/reviews'
    | '/api/generate-render'
    | '/design/new'
    | '/design/$id/gallery'
    | '/design/$id/refine'
    | '/design/$id/review'
    | '/design/$id/view/$idx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/designs'
    | '/admin/reviews'
    | '/api/generate-render'
    | '/design/new'
    | '/design/$id/gallery'
    | '/design/$id/refine'
    | '/design/$id/review'
    | '/design/$id/view/$idx'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/designs'
    | '/admin_/reviews'
    | '/api/generate-render'
    | '/design/new'
    | '/design/$id/gallery'
    | '/design/$id/refine'
    | '/design/$id/review'
    | '/design/$id/view/$idx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DesignsRoute: typeof DesignsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  ApiGenerateRenderRoute: typeof ApiGenerateRenderRoute
  DesignNewRoute: typeof DesignNewRoute
  DesignIdGalleryRoute: typeof DesignIdGalleryRoute
  DesignIdRefineRoute: typeof DesignIdRefineRoute
  DesignIdReviewRoute: typeof DesignIdReviewRoute
  DesignIdViewIdxRoute: typeof DesignIdViewIdxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/designs': {
      id: '/designs'
      path: '/designs'
      fullPath: '/designs'
      preLoaderRoute: typeof DesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/new': {
      id: '/design/new'
      path: '/design/new'
      fullPath: '/design/new'
      preLoaderRoute: typeof DesignNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-render': {
      id: '/api/generate-render'
      path: '/api/generate-render'
      fullPath: '/api/generate-render'
      preLoaderRoute: typeof ApiGenerateRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/reviews': {
      id: '/admin_/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id/review': {
      id: '/design/$id/review'
      path: '/design/$id/review'
      fullPath: '/design/$id/review'
      preLoaderRoute: typeof DesignIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id/refine': {
      id: '/design/$id/refine'
      path: '/design/$id/refine'
      fullPath: '/design/$id/refine'
      preLoaderRoute: typeof DesignIdRefineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id/gallery': {
      id: '/design/$id/gallery'
      path: '/design/$id/gallery'
      fullPath: '/design/$id/gallery'
      preLoaderRoute: typeof DesignIdGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id/view/$idx': {
      id: '/design/$id/view/$idx'
      path: '/design/$id/view/$idx'
      fullPath: '/design/$id/view/$idx'
      preLoaderRoute: typeof DesignIdViewIdxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DesignsRoute: DesignsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  ApiGenerateRenderRoute: ApiGenerateRenderRoute,
  DesignNewRoute: DesignNewRoute,
  DesignIdGalleryRoute: DesignIdGalleryRoute,
  DesignIdRefineRoute: DesignIdRefineRoute,
  DesignIdReviewRoute: DesignIdReviewRoute,
  DesignIdViewIdxRoute: DesignIdViewIdxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
